### ISSUE TITLE
Missing 's' in "https" break your link

### ISSUE THREAD

**Issue by aloisdg** [wbalbo/wbalbo#1]
Hi!

It seems that the link is broken because there is a missing 's'.  Try with `https://github-readme-streak-stats.herokuapp.com` instead of `http://github-readme-streak-stats.herokuapp.com`

result:

[![GitHub Streak](https://github-readme-streak-stats.herokuapp.com?user=wbalbo&theme=Javascript-dark)](https://git.io/streak-stats)

Thank you for your contributions to Cardidy :)

**Comment by wbalbo** [comment]
Hi, thanks.

Is a bit strange, I changed to HTTPS, and seems that still doesn't work.

**Comment by aloisdg** [comment]
Maybe with some space after dark to cut the link?

![image](https://user-images.githubusercontent.com/3449303/137596060-6d77629b-a6d3-4308-aab9-96156c676c3e.png)

`[ ![GitHub Streak](https://github-readme-streak-stats.herokuapp.com?user=wbalbo&theme=Javascript-dark ) ](https://git.io/streak-stats)`

[ ![GitHub Streak](https://github-readme-streak-stats.herokuapp.com?user=wbalbo&theme=Javascript-dark ) ](https://git.io/streak-stats)

**Comment by wbalbo** [comment]
Very strange because you can post perfectly the image but when I edit the file the links or the Github Streak command is not recognized

**Comment by wbalbo** [comment]
I "solved" transforming into an image pointing to my stats haha.

Thanks for your help!

**Comment by aloisdg** [comment]
glad you figure it out
